// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/nicclusterpolicy-crd.yaml --derive Default --derive PartialEq
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[kube(
    group = "mellanox.com",
    version = "v1alpha1",
    kind = "NicClusterPolicy",
    plural = "nicclusterpolicies"
)]
#[kube(status = "NicClusterPolicyStatus")]
#[kube(schema = "disabled")]
#[kube(derive = "Default")]
#[kube(derive = "PartialEq")]
pub struct NicClusterPolicySpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deploymentNodeAffinity"
    )]
    pub deployment_node_affinity: Option<NicClusterPolicyDeploymentNodeAffinity>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deploymentTolerations"
    )]
    pub deployment_tolerations: Option<Vec<NicClusterPolicyDeploymentTolerations>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "docaTelemetryService"
    )]
    pub doca_telemetry_service: Option<NicClusterPolicyDocaTelemetryService>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "ibKubernetes"
    )]
    pub ib_kubernetes: Option<NicClusterPolicyIbKubernetes>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nicConfigurationOperator"
    )]
    pub nic_configuration_operator: Option<NicClusterPolicyNicConfigurationOperator>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nicFeatureDiscovery"
    )]
    pub nic_feature_discovery: Option<NicClusterPolicyNicFeatureDiscovery>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeAffinity"
    )]
    pub node_affinity: Option<NicClusterPolicyNodeAffinity>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nvIpam")]
    pub nv_ipam: Option<NicClusterPolicyNvIpam>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "ofedDriver"
    )]
    pub ofed_driver: Option<NicClusterPolicyOfedDriver>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rdmaSharedDevicePlugin"
    )]
    pub rdma_shared_device_plugin: Option<NicClusterPolicyRdmaSharedDevicePlugin>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "secondaryNetwork"
    )]
    pub secondary_network: Option<NicClusterPolicySecondaryNetwork>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "spectrumXOperator"
    )]
    pub spectrum_x_operator: Option<NicClusterPolicySpectrumXOperator>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "sriovDevicePlugin"
    )]
    pub sriov_device_plugin: Option<NicClusterPolicySriovDevicePlugin>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tolerations: Option<Vec<NicClusterPolicyTolerations>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinity {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "preferredDuringSchedulingIgnoredDuringExecution"
    )]
    pub preferred_during_scheduling_ignored_during_execution: Option<
        Vec<NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution>,
    >,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "requiredDuringSchedulingIgnoredDuringExecution"
    )]
    pub required_during_scheduling_ignored_during_execution: Option<
        NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution,
    >,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
    pub preference: NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference,
    pub weight: i32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchFields")]
    pub match_fields: Option<Vec<NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution {
    #[serde(rename = "nodeSelectorTerms")]
    pub node_selector_terms: Vec<NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchFields")]
    pub match_fields: Option<Vec<NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDeploymentTolerations {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effect: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "tolerationSeconds"
    )]
    pub toleration_seconds: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDocaTelemetryService {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<NicClusterPolicyDocaTelemetryServiceConfig>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyDocaTelemetryServiceContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDocaTelemetryServiceConfig {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "fromConfigMap"
    )]
    pub from_config_map: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyDocaTelemetryServiceContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyIbKubernetes {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyIbKubernetesContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    #[serde(rename = "pKeyGUIDPoolRangeEnd")]
    pub p_key_guid_pool_range_end: String,
    #[serde(rename = "pKeyGUIDPoolRangeStart")]
    pub p_key_guid_pool_range_start: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "periodicUpdateSeconds"
    )]
    pub periodic_update_seconds: Option<i64>,
    pub repository: String,
    #[serde(rename = "ufmSecret")]
    pub ufm_secret: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyIbKubernetesContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperator {
    #[serde(rename = "configurationDaemon")]
    pub configuration_daemon: NicClusterPolicyNicConfigurationOperatorConfigurationDaemon,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "logLevel")]
    pub log_level: Option<NicClusterPolicyNicConfigurationOperatorLogLevel>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nicFirmwareStorage"
    )]
    pub nic_firmware_storage: Option<NicClusterPolicyNicConfigurationOperatorNicFirmwareStorage>,
    pub operator: NicClusterPolicyNicConfigurationOperatorOperator,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperatorConfigurationDaemon {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources:
        Option<Vec<NicClusterPolicyNicConfigurationOperatorConfigurationDaemonContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperatorConfigurationDaemonContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub enum NicClusterPolicyNicConfigurationOperatorLogLevel {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "debug")]
    Debug,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperatorNicFirmwareStorage {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "availableStorageSize"
    )]
    pub available_storage_size: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pvcName")]
    pub pvc_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "storageClassName"
    )]
    pub storage_class_name: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperatorOperator {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources:
        Option<Vec<NicClusterPolicyNicConfigurationOperatorOperatorContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicConfigurationOperatorOperatorContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicFeatureDiscovery {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyNicFeatureDiscoveryContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNicFeatureDiscoveryContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinity {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "preferredDuringSchedulingIgnoredDuringExecution"
    )]
    pub preferred_during_scheduling_ignored_during_execution:
        Option<Vec<NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "requiredDuringSchedulingIgnoredDuringExecution"
    )]
    pub required_during_scheduling_ignored_during_execution:
        Option<NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
    pub preference:
        NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference,
    pub weight: i32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchFields")]
    pub match_fields: Option<Vec<NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution {
    #[serde(rename = "nodeSelectorTerms")]
    pub node_selector_terms: Vec<
        NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms,
    >,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchFields")]
    pub match_fields: Option<Vec<NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields
{
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNvIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyNvIpamContainerResources>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "enableWebhook"
    )]
    pub enable_webhook: Option<bool>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyNvIpamContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriver {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "certConfig"
    )]
    pub cert_config: Option<NicClusterPolicyOfedDriverCertConfig>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyOfedDriverContainerResources>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<NicClusterPolicyOfedDriverEnv>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "forcePrecompiled"
    )]
    pub force_precompiled: Option<bool>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "livenessProbe"
    )]
    pub liveness_probe: Option<NicClusterPolicyOfedDriverLivenessProbe>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "readinessProbe"
    )]
    pub readiness_probe: Option<NicClusterPolicyOfedDriverReadinessProbe>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "repoConfig"
    )]
    pub repo_config: Option<NicClusterPolicyOfedDriverRepoConfig>,
    pub repository: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "startupProbe"
    )]
    pub startup_probe: Option<NicClusterPolicyOfedDriverStartupProbe>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "terminationGracePeriodSeconds"
    )]
    pub termination_grace_period_seconds: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "upgradePolicy"
    )]
    pub upgrade_policy: Option<NicClusterPolicyOfedDriverUpgradePolicy>,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverCertConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnv {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "valueFrom")]
    pub value_from: Option<NicClusterPolicyOfedDriverEnvValueFrom>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnvValueFrom {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configMapKeyRef"
    )]
    pub config_map_key_ref: Option<NicClusterPolicyOfedDriverEnvValueFromConfigMapKeyRef>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "fieldRef")]
    pub field_ref: Option<NicClusterPolicyOfedDriverEnvValueFromFieldRef>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "resourceFieldRef"
    )]
    pub resource_field_ref: Option<NicClusterPolicyOfedDriverEnvValueFromResourceFieldRef>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "secretKeyRef"
    )]
    pub secret_key_ref: Option<NicClusterPolicyOfedDriverEnvValueFromSecretKeyRef>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnvValueFromConfigMapKeyRef {
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnvValueFromFieldRef {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "apiVersion"
    )]
    pub api_version: Option<String>,
    #[serde(rename = "fieldPath")]
    pub field_path: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnvValueFromResourceFieldRef {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerName"
    )]
    pub container_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub divisor: Option<IntOrString>,
    pub resource: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverEnvValueFromSecretKeyRef {
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverLivenessProbe {
    #[serde(rename = "initialDelaySeconds")]
    pub initial_delay_seconds: i64,
    #[serde(rename = "periodSeconds")]
    pub period_seconds: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverReadinessProbe {
    #[serde(rename = "initialDelaySeconds")]
    pub initial_delay_seconds: i64,
    #[serde(rename = "periodSeconds")]
    pub period_seconds: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverRepoConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverStartupProbe {
    #[serde(rename = "initialDelaySeconds")]
    pub initial_delay_seconds: i64,
    #[serde(rename = "periodSeconds")]
    pub period_seconds: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverUpgradePolicy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "autoUpgrade"
    )]
    pub auto_upgrade: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drain: Option<NicClusterPolicyOfedDriverUpgradePolicyDrain>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxParallelUpgrades"
    )]
    pub max_parallel_upgrades: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "safeLoad")]
    pub safe_load: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "waitForCompletion"
    )]
    pub wait_for_completion: Option<NicClusterPolicyOfedDriverUpgradePolicyWaitForCompletion>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverUpgradePolicyDrain {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deleteEmptyDir"
    )]
    pub delete_empty_dir: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "podSelector"
    )]
    pub pod_selector: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "timeoutSeconds"
    )]
    pub timeout_seconds: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyOfedDriverUpgradePolicyWaitForCompletion {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "podSelector"
    )]
    pub pod_selector: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "timeoutSeconds"
    )]
    pub timeout_seconds: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyRdmaSharedDevicePlugin {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicyRdmaSharedDevicePluginContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "useCdi")]
    pub use_cdi: Option<bool>,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyRdmaSharedDevicePluginContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetwork {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "cniPlugins"
    )]
    pub cni_plugins: Option<NicClusterPolicySecondaryNetworkCniPlugins>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "ipamPlugin"
    )]
    pub ipam_plugin: Option<NicClusterPolicySecondaryNetworkIpamPlugin>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipoib: Option<NicClusterPolicySecondaryNetworkIpoib>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multus: Option<NicClusterPolicySecondaryNetworkMultus>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkCniPlugins {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources:
        Option<Vec<NicClusterPolicySecondaryNetworkCniPluginsContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkCniPluginsContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkIpamPlugin {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources:
        Option<Vec<NicClusterPolicySecondaryNetworkIpamPluginContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkIpamPluginContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkIpoib {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicySecondaryNetworkIpoibContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkIpoibContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkMultus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicySecondaryNetworkMultusContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySecondaryNetworkMultusContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySpectrumXOperator {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicySpectrumXOperatorContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySpectrumXOperatorContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySriovDevicePlugin {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerResources"
    )]
    pub container_resources: Option<Vec<NicClusterPolicySriovDevicePluginContainerResources>>,
    pub image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    pub repository: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "useCdi")]
    pub use_cdi: Option<bool>,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicySriovDevicePluginContainerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyTolerations {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effect: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "tolerationSeconds"
    )]
    pub toleration_seconds: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyStatus {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "appliedStates"
    )]
    pub applied_states: Option<Vec<NicClusterPolicyStatusAppliedStates>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub state: NicClusterPolicyStatusState,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct NicClusterPolicyStatusAppliedStates {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    pub name: String,
    pub state: NicClusterPolicyStatusAppliedStatesState,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub enum NicClusterPolicyStatusAppliedStatesState {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "notReady")]
    NotReady,
    #[serde(rename = "ignore")]
    #[default]
    Ignore,
    #[serde(rename = "error")]
    Error,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub enum NicClusterPolicyStatusState {
    #[serde(rename = "ignore")]
    #[default]
    Ignore,
    #[serde(rename = "notReady")]
    NotReady,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "error")]
    Error,
}
